moroz config name must be global.toml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,7 +48,7 @@ jobs:
       - name: install and run moroz
         run: |
           go install github.com/kallsyms/moroz/cmd/moroz@ee0a5a7b
-          ~/go/bin/moroz -configs="$GITHUB_WORKSPACE/Testing/global.toml" -use-tls=false &
+          ~/go/bin/moroz -configs="$GITHUB_WORKSPACE/Testing/integration/configs/moroz_default/global.toml" -use-tls=false &
       - name: start santa and sync
         run: |
           bazel run :reload --define=SANTA_BUILD_TYPE=adhoc
@@ -57,9 +57,35 @@ jobs:
         run: bazel test //Testing/integration:integration_tests
       - name: test config changes
         run: |
+          set -x
           bazel run //Testing/integration:install_profile -- Testing/integration/configs/usb-block.mobileconfig
           if [[ "$(santactl status --json | jq .daemon.block_usb)" != "true" ]]; then
             echo "USB blocking config change didnt take effect" >&2
+            exit 1
+          fi
+      - name: test sync server changes
+        run: |
+          set -x
+          bazel run //Testing/integration:install_profile -- Testing/integration/configs/minimal.mobileconfig
+          bazel run :reload --define=SANTA_BUILD_TYPE=adhoc
+          sudo santactl sync --debug
+          if [[ "$(santactl status --json | jq .daemon.block_usb)" != "false" ]]; then
+            echo "USB blocking enabled with minimal config" >&2
+            exit 1
+          fi
+          killall moroz
+          ~/go/bin/moroz -configs="$GITHUB_WORKSPACE/Testing/integration/configs/moroz_changed/global.toml" -use-tls=false &
+          sudo santactl sync --debug
+          if [[ "$(santactl status --json | jq .daemon.block_usb)" != "true" ]]; then
+            echo "USB blocking config change didnt take effect" >&2
+            exit 1
+          fi
+          set +e
+          ./Source/santad/testdata/binaryrules/badbinary
+          previously_blocklisted=$?
+          set -e
+          if [[ $previously_blocklisted != 0 ]]; then
+            echo "Removal from blocklist failed" >&2
             exit 1
           fi
       - name: schedule poweroff
